ang_arr:
- -1.64
- 2.14
- 400
average_angle: null
center_thresh: 0.0
chunk_size: 500000
clip_negative: false
cluster_function: DBSCAN
cluster_type: all
debug: false
do_clustering: true
do_mask: false
do_stamp_filter: true
encode_num_bytes: -1
eps: 0.03
flag_keys:
- BAD
- EDGE
- NO_DATA
- SUSPECT
- UNMASKEDNAN
gpu_filter: true
im_filepath: null
ind_output_files: true
known_obj_jpl: false
known_obj_obs: 3
known_obj_thresh: null
lh_level: 10.0
mask_bit_vector: null
mask_bits_dict:
  BAD: 0
  CLIPPED: 9
  CR: 3
  CROSSTALK: 10
  DETECTED: 5
  DETECTED_NEGATIVE: 6
  EDGE: 4
  INEXACT_PSF: 11
  INTRP: 2
  NOT_DEBLENDED: 12
  NO_DATA: 8
  REJECTED: 13
  SAT: 1
  SENSOR_EDGE: 14
  SUSPECT: 7
  UNMASKEDNAN: 15
mask_grow: 10
mask_num_images: 2
mask_threshold: null
max_lh: 1000.0
mjd_lims: null
mom_lims:
- 35.5
- 35.5
- 2.0
- 0.3
- 0.3
num_cores: 1
num_obs: 10
output_suffix: results
peak_offset:
- 2.0
- 2.0
psf_file: null
psf_val: 1.4
repeated_flag_keys: []
res_filepath: /mmfs1/gscratch/escience/wbeebe/kbmod/results/1000_imgs_5_16_slow
result_filename: /mmfs1/gscratch/escience/wbeebe/kbmod/results/1000_imgs_5_16_slow/full_results.ecsv
save_all_stamps: false
sigmaG_lims:
- 25
- 75
stamp_radius: 10
stamp_type: sum
time_file: null
v_arr:
- 10
- 65
- 200
x_pixel_bounds: null
x_pixel_buffer: null
y_pixel_bounds: null
y_pixel_buffer: null
